export const ALL_APPRECIATIONS_REQUEST = "ALL_APPRECIATIONS_REQUEST";
export const ALL_APPRECIATIONS_SUCCESS = "ALL_APPRECIATIONS_SUCCESS";
export const ALL_APPRECIATIONS_FAIL = "ALL_APPRECIATIONS_FAIL";

export const ADMIN_APPRECIATIONS_REQUEST = "ADMIN_APPRECIATIONS_REQUEST";
export const ADMIN_APPRECIATIONS_SUCCESS = "ADMIN_APPRECIATIONS_SUCCESS";
export const ADMIN_APPRECIATIONS_FAIL = "ADMIN_APPRECIATIONS_FAIL";

export const USER_APPRECIATIONS_REQUEST = "USER_APPRECIATIONS_REQUEST";
export const USER_APPRECIATIONS_SUCCESS = "USER_APPRECIATIONS_SUCCESS";
export const USER_APPRECIATIONS_FAIL = "USER_APPRECIATIONS_FAIL";

export const NEW_APPRECIATION_REQUEST = "NEW_APPRECIATION_REQUEST";
export const NEW_APPRECIATION_SUCCESS = "NEW_APPRECIATION_SUCCESS";
export const NEW_APPRECIATION_RESET = "NEW_APPRECIATION_RESET";
export const NEW_APPRECIATION_FAIL = "NEW_APPRECIATION_FAIL";

export const UPDATE_APPRECIATION_REQUEST = "UPDATE_APPRECIATION_REQUEST";
export const UPDATE_APPRECIATION_SUCCESS = "UPDATE_APPRECIATION_SUCCESS";
export const UPDATE_APPRECIATION_RESET = "UPDATE_APPRECIATION_RESET";
export const UPDATE_APPRECIATION_FAIL = "UPDATE_APPRECIATION_FAIL";

export const DELETE_APPRECIATION_REQUEST = "DELETE_APPRECIATION_REQUEST";
export const DELETE_APPRECIATION_SUCCESS = "DELETE_APPRECIATION_SUCCESS";
export const DELETE_APPRECIATION_RESET = "DELETE_APPRECIATION_RESET";
export const DELETE_APPRECIATION_FAIL = "DELETE_APPRECIATION_FAIL";

export const APPRECIATION_DETAILS_REQUEST = "APPRECIATION_DETAILS_REQUEST";
export const APPRECIATION_DETAILS_SUCCESS = "APPRECIATION_DETAILS_SUCCESS";
export const APPRECIATION_DETAILS_FAIL = "APPRECIATION_DETAILS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
