export const ALL_APPRECIATIONS_REQUEST = "ALL_APPRECIATIONS_REQUEST";
export const ALL_APPRECIATIONS_SUCCESS = "ALL_APPRECIATIONS_SUCCESS";
export const ALL_APPRECIATIONS_FAIL = "ALL_APPRECIATIONS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
