export const ALL_HEROES_REQUEST = "ALL_HEROES_REQUEST";
export const ALL_HEROES_SUCCESS = "ALL_HEROES_SUCCESS";
export const ALL_HEROES_FAIL = "ALL_HEROES_FAIL";

export const HERO_DETAILS_REQUEST = "HERO_DETAILS_REQUEST";
export const HERO_DETAILS_SUCCESS = "HERO_DETAILS_SUCCESS";
export const HERO_DETAILS_FAIL = "HERO_DETAILS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
